<?php namespace App\Http\Controllers; use Illuminate\Http\Request;use App\Models\{Tenant,Channel,Topic,ContentAsset,Campaign,Competitor,BenchmarkCompany,SignalCheck,PerformanceEntry};
class ResourceController{private function cfg(Request $r){$p=$r->route()->getName();$n=str_ends_with($p,'.index')||str_contains($p,'.') ? substr($p,0,strrpos($p,'.')) : $p;return match($n){'topics'=>[Topic::class,'topics','Thema'], 'assets'=>[ContentAsset::class,'assets','Inhalt'], 'campaigns'=>[Campaign::class,'campaigns','Kampagne'], 'signal-checks'=>[SignalCheck::class,'signal_checks','Lagecheck'], 'settings/tenants'=>[Tenant::class,'settings.tenants','Mandant'], 'settings/channels'=>[Channel::class,'settings.channels','Kanäle'], 'settings/competitors'=>[Competitor::class,'settings.competitors','Wettbewerber'], default=>[BenchmarkCompany::class,'settings.benchmarks','Benchmark']};}
function index(Request $r){[$m,$v,$label]=$this->cfg($r);$q=$m::query(); if(!in_array($m,[Tenant::class,Channel::class]))$q->where('tenant_id',session('active_tenant_id')); if($m===Tenant::class)$items=$r->user()->tenants; else $items=$q->latest()->get(); return view('common.index',compact('items','label','v'));}
function create(Request $r){[$m,$v,$label]=$this->cfg($r);return view('common.form',$this->data($v,$label,new $m));}
function store(Request $r){[$m,$v,$label]=$this->cfg($r);$data=$this->validated($r,$m); if(!in_array($m,[Tenant::class,Channel::class]))$data['tenant_id']=session('active_tenant_id');$item=$m::create($data);$this->sync($r,$item,$m); if($m===Tenant::class){$r->user()->tenants()->syncWithoutDetaching([$item->id]);} return redirect()->route($v.'.index')->with('status',$label.' gespeichert.');}
function show(Request $r,$id){[$m,$v,$label]=$this->cfg($r);$item=$m::findOrFail($id);return view('common.show',$this->data($v,$label,$item));}
function edit(Request $r,$id){[$m,$v,$label]=$this->cfg($r);$item=$m::findOrFail($id);return view('common.form',$this->data($v,$label,$item));}
function update(Request $r,$id){[$m,$v,$label]=$this->cfg($r);$item=$m::findOrFail($id);$item->update($this->validated($r,$m));$this->sync($r,$item,$m);return redirect()->route($v.'.index')->with('status',$label.' gespeichert.');}
function destroy(Request $r,$id){[$m,$v,$label]=$this->cfg($r);$m::findOrFail($id)->delete();return back()->with('status',$label.' gelöscht.');}
function performance(Request $r, Campaign $campaign){abort_unless($campaign->tenant_id==session('active_tenant_id'),403);$d=$r->validate(['reach'=>'nullable|integer','clicks'=>'nullable|integer','engagement'=>'nullable|integer','conversions'=>'nullable|integer','rating'=>'required|in:weak,normal,strong','summary'=>'nullable','notes'=>'nullable']);$d['tenant_id']=$campaign->tenant_id;$campaign->performanceEntries()->create($d);return back();}
private function validated($r,$m){return $r->validate(['name'=>'nullable|string|max:255','title'=>'nullable|string|max:255','industry'=>'nullable','website'=>'nullable|url','description'=>'nullable','tone_of_voice'=>'nullable','notes'=>'nullable','color'=>'nullable','icon'=>'nullable','target_audience'=>'nullable','keywords'=>'nullable','status'=>'nullable|string','topic_id'=>'nullable|integer','channel_id'=>'nullable|integer','asset_type'=>'nullable|string','url'=>'nullable|url','publish_date'=>'nullable|date','reusable_status'=>'nullable|string','start_date'=>'nullable|date','end_date'=>'nullable|date','responsible_name'=>'nullable','market_signal_notes'=>'nullable','competitor_notes'=>'nullable','benchmark_notes'=>'nullable','internal_content_summary'=>'nullable','ai_summary'=>'nullable','cautious_next_steps'=>'nullable','channels'=>'array','assets'=>'array']);}
private function sync($r,$item,$m){ if($m===Topic::class)$item->channels()->sync($r->input('channels',[])); if($m===Campaign::class)$item->assets()->sync($r->input('assets',[])); if($m===Channel::class && $r->has('active')){auth()->user()->activeTenant?->channels()->syncWithoutDetaching([$item->id]);}}
private function data($v,$label,$item){$tid=session('active_tenant_id');return ['v'=>$v,'label'=>$label,'item'=>$item,'topics'=>Topic::where('tenant_id',$tid)->get(),'channels'=>auth()->user()?->activeTenant?->channels ?? Channel::all(),'assets'=>ContentAsset::where('tenant_id',$tid)->get()];}}
